// this file was generated by the xRM Test Framework VS Extension

#region Imports

using System;
using Microsoft.Xrm.Sdk;
using Yagasoft.Libraries.Common;
using Yagasoft.Libraries.Plugins.Messages.Code;

#endregion

namespace Yagasoft.Libraries.Plugins.Messages.Plugins
{
	/// <summary>
	///     Generate a unique message code.<br />
	///     Version: 1.1.1
	/// </summary>
	public class PreOpCreateMessageGenerateCode : IPlugin
	{
		public void Execute(IServiceProvider serviceProvider)
		{
			new PreOpCreateMessageGenerateCodeLogic().Execute(this, serviceProvider, PluginUser.ContextUser);
		}
	}

	internal class PreOpCreateMessageGenerateCodeLogic()
		: PluginLogic<PreOpCreateMessageGenerateCode>("Create", PluginStage.PreOperation, CustomMessage.EntityLogicalName)
	{
		protected override void ExecuteLogic()
		{
			var customMessage = GetTarget<CustomMessage>();
			var generatedCode = CodeGenerator.GenerateCode(customMessage, Service, Log);

			if (generatedCode.IsEmpty())
			{
				return;
			}

			customMessage.ID = generatedCode;
		}
	}
}
